version: "3"
services:
  db:
    image: mariadb:10.3
    container_name: moneta-mariadb
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=klopaphere-votes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
      - "--skip-character-set-client-handshake"
      - "--default-storage-engine=innodb"
      - "--alter_algorithm=INPLACE"
      - "--innodb_autoinc_lock_mode=2"
      - "--innodb_force_primary_key=1"
      - "--lower_case_table_names=1"
    ports:
      - 3306:3306
