version: "3"
services:
  db:
    image: mariadb:10.3
    container_name: klopaphere-mariadb
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=klopaphere-votes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
      - "--skip-character-set-client-handshake"
      - "--default-storage-engine=innodb"
      - "--alter_algorithm=INPLACE"
      - "--innodb_autoinc_lock_mode=2"
      - "--innodb_force_primary_key=1"
      - "--lower_case_table_names=1"
    ports:
      - 3306:3306
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "demand:1:1,voting:1:1"
