FROM openjdk:8

ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
WORKDIR /deployments

EXPOSE 8080
USER 1001

CMD ["java", "-jar", "app.jar"]
