FROM registry.redhat.io/ubi8/ubi-minimal:latest
EXPOSE 8080
USER 1001

ADD application ./application

RUN mkdir -p /work
ADD config/cacerts /work/cacerts

CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djavax.net.ssl.trustStore=/work/cacerts"]
