### New Voting
POST http://127.0.0.1:8080/vote
Content-Type: application/json

{
  "product":  "Klopapier",
  "location": "53.6159766,9.9022919",
  "availability":  "NORMAL"
}

### New Voting (OCP)
POST https://api.klopaphere.de/vote
Content-Type: application/json

{
"product":  "Klopapier",
"location": "53.6159766,9.9022919",
"availability":  "NORMAL"
}

### OpenAPI Spec
GET http://127.0.0.1:8080/openapi

### Swagger UI
GET http://127.0.0.1:8080/swagger-ui

### Mock Products
GET http://127.0.0.1:8080/product

### Get All Votes
GET http://127.0.0.1:8080/vote

### New Demand
POST http://127.0.0.1:8080/demand
Content-Type: application/json

{
  "product":  "Klopapier",
  "location": "53.6159766,9.9022919"
}

### GET Heatmap for product in location
GET http://127.0.0.1:8080/heatmap/53.6159766,9.9022919/Klopapier

### Send current Location
POST http://127.0.0.1:8080/location
Content-Type: application/json

{
  "location": "53.6159766,9.9022919",
  "deviceToken": "myFancyDeviceToken"
}

###
