apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.global.name | lower | quote }}
  labels:
    app: {{ .Values.global.name | lower | quote }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.global.name }}:latest'
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk-8-rhel8:latest"
      noCache: true
      dockerfilePath: Dockerfile.ocp
    type: Docker
  triggers: []
  successfulBuildsHistoryLimit: {{ .Values.buildConfig.buildsHistoryLimits.successful }}
  failedBuildsHistoryLimit: {{ .Values.buildConfig.buildsHistoryLimits.failed }}
