apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.global.name | lower }}'
  labels:
    app: {{ .Values.global.name | lower | quote }}
spec:
  ports:
    - name: "8080-tcp"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.global.name | quote}}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
