global:
  name: "klopaphere-votes"
  managedBy: "AvengersVsVirus"

deploymentConfig:
  env:
    - name: KAFKA_HOST
      value: 'kafka.apps.ocp4.keithtenzer.com:443'
    - name: KAFKA_USER
      value: 'klopaphere'
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: klopaphere
          key: password
    - name: APP_DESCRIPTION
      value: "klopaphere-votes"
    - name: DB_HOST
      value: 'mariadb'
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mariadb
          key: database-user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb
          key: database-password
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: mariadb
          key: database-name
    - name: GOOGLE_API_KEY
      valueFrom:
        secretKeyRef:
          name: google-api
          key: GOOGLE_API_KEY
  livenessProbe:
    enabled: true
    path: '/health/live'
    port: 8080
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  readinessProbe:
    enabled: true
    path: '/health/ready'
    port: 8080
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  replicaCount: 1
  resourceRequestCpu: "250m"
  resourceLimitCpu: "1"
  resourceRequestRam: "800Mi"
  resourceLimitRam: "1200Mi"
  revisionHistoryLimit: 3
  port: 8080

buildConfig:
  buildsHistoryLimits:
    successful: 10
    failed: 10
  outputImageTag: latest
  env: []
